### ISSUE TITLE
Does Video tracking agent provides Video Quality Metrics or Events?

### ISSUE THREAD

**Issue by shehrooz-10p** [newrelic/video-videojs-js#6]
Hi,

I am using new relic to track videos and ads using New Relic VideoJS tracker instruments.

I have deployed the agent and the dashboard as listed in the following link.

[https://newrelic.com/blog/how-to-relic/tracking-your-videos-and-ads-with-new-relic](https://newrelic.com/blog/how-to-relic/tracking-your-videos-and-ads-with-new-relic)

Everything seems fine data is smoothly flowing to New Relic default dashboard. But, I am unable to find any information about Video Quality Metrics or Events.

It is mentioned in the following link that New Relic Video tracking agent provides Video Quality Metrics or Events including bitrate.

[https://newrelic.com/blog/how-to-relic/media-monitoring](https://newrelic.com/blog/how-to-relic/media-monitoring)

I have also explored data in new relic using NRQL and Data Explorer utiltity but I am unable to find any data related to Bitrate.

Could please guide me where i can find the follwoing metrics in new relic if they exist...

Video Quality Upscale
Percentage

Video Quality Downscale
Percentage

Average Bitrate

Live Stream
Latency

Or any other KPIs that new relic provides for Video Quality

Secondly, From where, I can get the List of the all the Metrics or Events that tracked by new relic video tracking agent?

Thank you,

Shehrooz

**Comment by shehrooz-10p** [comment]
@asllop @adwetzelnr @flaviohenriquecbc  Your help in this matter would be high appreciated.

**Comment by asllop** [comment]
Hi @shehrooz-10p ! All web video trackers use the New Relic Browser agent to report [PageAction events](https://docs.newrelic.com/docs/data-apis/custom-data/custom-events/report-browser-monitoring-custom-events-attributes/), and so, all events generated by this tracker have an `eventType` equal to `PageAction`. If you run the following NRQL you should be able to see your data:

```
SELECT * FROM PageAction
```

Each event has a specific meaning, and this is specified in the `actionName` field.

Currently we don't have a list that is specific to VideoJS, but you can check the [Roku Agent Video data model](https://github.com/newrelic/video-agent-roku/#roku-video), that is almost identical. You can also check our [video telemetry documentation wiki](https://github.com/newrelic-experimental/video-documentation/wiki), that is still work in progress, but could help you clarify some concepts.

I hope this helps.

**Comment by shehrooz-10p** [comment]
@asllop Thank you for your much-appreciated support. 

Is there a way to customize video trackers agent to track customized metrics related to video quality, such as Live Stream
Latency, Video Quality Upscale Percentage, and Video Quality Downscale Percentage.

I found "contentRenditionBitrate)" in "PageAction" can we use it as Average Bitrate for our Livestream?

Best,
Shehrooz

**Comment by asllop** [comment]
Hi @shehrooz-10p !

Yes you can customize the tracker in multiple ways, depending on your needs: you can subclass [VideojsTracker](https://github.com/newrelic/video-videojs-js/blob/master/src/tracker.js), or fork this repo and modify it. You can also call `send` methods in the tracker to send custom events programmatically.

Regarding "contentRenditionBitrate", this attribute informs the current bitrate used by the video stream (at the moment the event was sent), so you can use it to calculate KPIs related to bitrate.
